#!/bin/bash

cd "${CKANHOME:-${HOME}/Downloads}"

# Now print something if the program isn't here, in case anyone else ever uses this program.
if [ ! -s ckan ]
then
	echo 'ckan not found. Set CKANHOME to its location. The default is $HOME/Downloads.'
	exit 2
fi

# Use CKAN's default path to find the registry.json file
while read -r LINE
do
	if [ $(echo "${LINE}" | awk '{print $3}') = Yes ]
	then
		REGISTRY=$(echo "${LINE}" | awk -F '  +' '{print $4}')/CKAN/registry.json
		break
	fi
done < <(mono ckan ksp list | tail -n +3)

echo "${REGISTRY}"
