#!/bin/bash

cd "${CKANHOME:-${HOME}/Downloads}"

# Now print something if the program isn't here, in case anyone else ever uses this program.
if [ ! -s ckan ]
then
	echo 'ckan not found. Set CKANHOME to its location. The default is $HOME/Downloads.'
	echo 'Note that we will also store three files in the same folder:'
	echo '	.ckan-avail.cur 	The currently available package list'
	echo '	.ckan-avail.prev	The available package list from the previous run, for comparison'
	echo '	.ckan-avail.diff	The diff of the previous two files'
	exit 2
fi

# Use CKAN's default path to find the registry.json file 
while read -r LINE
do
	if [ $(echo "${LINE}" | cut -c 24-26) = Yes ]
	then
		REGISTRY=$(echo "${LINE}" | cut -c 33- )/CKAN/registry.json
		break
	fi
done < <(mono ckan ksp list | tail -n +3)

echo "${REGISTRY}"
