#!/bin/bash

MASS=${1:-25000}
OX=${2:-440}

# Normally liquid fuel is derived from oxidizer
LF=${3:-$(bc -l <<<"$OX*270/330")}

if [ $(bc -l <<<"$OX*270/330 > $LF") -eq '0' ]
then
	OX=$(bc -l <<<"$LF*330/270")
fi

# We assume LV-N engines
ISP=${4:-800}

# Gravitational constant
G=9.81

printf '%.1f\n' $(bc -l <<<"$G*$ISP*l($MASS/($MASS-5*($OX+$LF)))")
